; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
custom_app_name = ESPDoorLock
custom_app_version = 1.1.0NM
extra_scripts = pre:set_version.py

[env:esp32doit-devkit-v1]
build_src_filter = +<*> -<test_*>
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.9.4
	nitek/NDEF_MFRC522@^2.0.0

[env:ntag215_cardhandler]
build_src_filter = -<*> +<Config.h> +<test_ntag215_cardhandler.cpp>
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12
	nitek/NDEF_MFRC522@^2.0.0
